package com.cn.cust.dao;

import com.cn.cust.entities.Happayteachersdays;
import com.cn.cust.entities.HappayteachersdaysExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HappayteachersdaysMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table happayteachersdays
     *
     * @mbggenerated Sat Sep 10 23:42:59 CST 2016
     */
    int countByExample(HappayteachersdaysExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table happayteachersdays
     *
     * @mbggenerated Sat Sep 10 23:42:59 CST 2016
     */
    int deleteByExample(HappayteachersdaysExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table happayteachersdays
     *
     * @mbggenerated Sat Sep 10 23:42:59 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table happayteachersdays
     *
     * @mbggenerated Sat Sep 10 23:42:59 CST 2016
     */
    int insert(Happayteachersdays record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table happayteachersdays
     *
     * @mbggenerated Sat Sep 10 23:42:59 CST 2016
     */
    int insertSelective(Happayteachersdays record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table happayteachersdays
     *
     * @mbggenerated Sat Sep 10 23:42:59 CST 2016
     */
    List<Happayteachersdays> selectByExample(HappayteachersdaysExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table happayteachersdays
     *
     * @mbggenerated Sat Sep 10 23:42:59 CST 2016
     */
    Happayteachersdays selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table happayteachersdays
     *
     * @mbggenerated Sat Sep 10 23:42:59 CST 2016
     */
    int updateByExampleSelective(@Param("record") Happayteachersdays record, @Param("example") HappayteachersdaysExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table happayteachersdays
     *
     * @mbggenerated Sat Sep 10 23:42:59 CST 2016
     */
    int updateByExample(@Param("record") Happayteachersdays record, @Param("example") HappayteachersdaysExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table happayteachersdays
     *
     * @mbggenerated Sat Sep 10 23:42:59 CST 2016
     */
    int updateByPrimaryKeySelective(Happayteachersdays record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table happayteachersdays
     *
     * @mbggenerated Sat Sep 10 23:42:59 CST 2016
     */
    int updateByPrimaryKey(Happayteachersdays record);
    
    /**
     * Gafker no page
     * @return
     */
    List<Happayteachersdays> selectAll();
}