package com.cn.cust.entities;

import java.util.Date;

public class Feedback {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback.Id
     *
     * @mbggenerated Sun Sep 11 14:51:54 CST 2016
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback.Category
     *
     * @mbggenerated Sun Sep 11 14:51:54 CST 2016
     */
    private String category;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback.Content
     *
     * @mbggenerated Sun Sep 11 14:51:54 CST 2016
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback.ResponseContent
     *
     * @mbggenerated Sun Sep 11 14:51:54 CST 2016
     */
    private String responsecontent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback.Title
     *
     * @mbggenerated Sun Sep 11 14:51:54 CST 2016
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback.WeChat
     *
     * @mbggenerated Sun Sep 11 14:51:54 CST 2016
     */
    private String wechat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback.WeQQ
     *
     * @mbggenerated Sun Sep 11 14:51:54 CST 2016
     */
    private String weqq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback.Taobao
     *
     * @mbggenerated Sun Sep 11 14:51:54 CST 2016
     */
    private String taobao;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback.Phone
     *
     * @mbggenerated Sun Sep 11 14:51:54 CST 2016
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback.Address
     *
     * @mbggenerated Sun Sep 11 14:51:54 CST 2016
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback.IpAddress
     *
     * @mbggenerated Sun Sep 11 14:51:54 CST 2016
     */
    private String ipaddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback.UserAgent
     *
     * @mbggenerated Sun Sep 11 14:51:54 CST 2016
     */
    private String useragent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback.CreateTime
     *
     * @mbggenerated Sun Sep 11 14:51:54 CST 2016
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback.ResponseTime
     *
     * @mbggenerated Sun Sep 11 14:51:54 CST 2016
     */
    private Date responsetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback.UpdateUser
     *
     * @mbggenerated Sun Sep 11 14:51:54 CST 2016
     */
    private String updateuser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback.UpdateTime
     *
     * @mbggenerated Sun Sep 11 14:51:54 CST 2016
     */
    private Date updatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback.FeedBackUser
     *
     * @mbggenerated Sun Sep 11 14:51:54 CST 2016
     */
    private String feedbackuser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback.IsShow
     *
     * @mbggenerated Sun Sep 11 14:51:54 CST 2016
     */
    private Integer isshow;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback.Id
     *
     * @return the value of feedback.Id
     *
     * @mbggenerated Sun Sep 11 14:51:54 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback.Id
     *
     * @param id the value for feedback.Id
     *
     * @mbggenerated Sun Sep 11 14:51:54 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback.Category
     *
     * @return the value of feedback.Category
     *
     * @mbggenerated Sun Sep 11 14:51:54 CST 2016
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback.Category
     *
     * @param category the value for feedback.Category
     *
     * @mbggenerated Sun Sep 11 14:51:54 CST 2016
     */
    public void setCategory(String category) {
        this.category = category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback.Content
     *
     * @return the value of feedback.Content
     *
     * @mbggenerated Sun Sep 11 14:51:54 CST 2016
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback.Content
     *
     * @param content the value for feedback.Content
     *
     * @mbggenerated Sun Sep 11 14:51:54 CST 2016
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback.ResponseContent
     *
     * @return the value of feedback.ResponseContent
     *
     * @mbggenerated Sun Sep 11 14:51:54 CST 2016
     */
    public String getResponsecontent() {
        return responsecontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback.ResponseContent
     *
     * @param responsecontent the value for feedback.ResponseContent
     *
     * @mbggenerated Sun Sep 11 14:51:54 CST 2016
     */
    public void setResponsecontent(String responsecontent) {
        this.responsecontent = responsecontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback.Title
     *
     * @return the value of feedback.Title
     *
     * @mbggenerated Sun Sep 11 14:51:54 CST 2016
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback.Title
     *
     * @param title the value for feedback.Title
     *
     * @mbggenerated Sun Sep 11 14:51:54 CST 2016
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback.WeChat
     *
     * @return the value of feedback.WeChat
     *
     * @mbggenerated Sun Sep 11 14:51:54 CST 2016
     */
    public String getWechat() {
        return wechat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback.WeChat
     *
     * @param wechat the value for feedback.WeChat
     *
     * @mbggenerated Sun Sep 11 14:51:54 CST 2016
     */
    public void setWechat(String wechat) {
        this.wechat = wechat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback.WeQQ
     *
     * @return the value of feedback.WeQQ
     *
     * @mbggenerated Sun Sep 11 14:51:54 CST 2016
     */
    public String getWeqq() {
        return weqq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback.WeQQ
     *
     * @param weqq the value for feedback.WeQQ
     *
     * @mbggenerated Sun Sep 11 14:51:54 CST 2016
     */
    public void setWeqq(String weqq) {
        this.weqq = weqq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback.Taobao
     *
     * @return the value of feedback.Taobao
     *
     * @mbggenerated Sun Sep 11 14:51:54 CST 2016
     */
    public String getTaobao() {
        return taobao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback.Taobao
     *
     * @param taobao the value for feedback.Taobao
     *
     * @mbggenerated Sun Sep 11 14:51:54 CST 2016
     */
    public void setTaobao(String taobao) {
        this.taobao = taobao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback.Phone
     *
     * @return the value of feedback.Phone
     *
     * @mbggenerated Sun Sep 11 14:51:54 CST 2016
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback.Phone
     *
     * @param phone the value for feedback.Phone
     *
     * @mbggenerated Sun Sep 11 14:51:54 CST 2016
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback.Address
     *
     * @return the value of feedback.Address
     *
     * @mbggenerated Sun Sep 11 14:51:54 CST 2016
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback.Address
     *
     * @param address the value for feedback.Address
     *
     * @mbggenerated Sun Sep 11 14:51:54 CST 2016
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback.IpAddress
     *
     * @return the value of feedback.IpAddress
     *
     * @mbggenerated Sun Sep 11 14:51:54 CST 2016
     */
    public String getIpaddress() {
        return ipaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback.IpAddress
     *
     * @param ipaddress the value for feedback.IpAddress
     *
     * @mbggenerated Sun Sep 11 14:51:54 CST 2016
     */
    public void setIpaddress(String ipaddress) {
        this.ipaddress = ipaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback.UserAgent
     *
     * @return the value of feedback.UserAgent
     *
     * @mbggenerated Sun Sep 11 14:51:54 CST 2016
     */
    public String getUseragent() {
        return useragent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback.UserAgent
     *
     * @param useragent the value for feedback.UserAgent
     *
     * @mbggenerated Sun Sep 11 14:51:54 CST 2016
     */
    public void setUseragent(String useragent) {
        this.useragent = useragent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback.CreateTime
     *
     * @return the value of feedback.CreateTime
     *
     * @mbggenerated Sun Sep 11 14:51:54 CST 2016
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback.CreateTime
     *
     * @param createtime the value for feedback.CreateTime
     *
     * @mbggenerated Sun Sep 11 14:51:54 CST 2016
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback.ResponseTime
     *
     * @return the value of feedback.ResponseTime
     *
     * @mbggenerated Sun Sep 11 14:51:54 CST 2016
     */
    public Date getResponsetime() {
        return responsetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback.ResponseTime
     *
     * @param responsetime the value for feedback.ResponseTime
     *
     * @mbggenerated Sun Sep 11 14:51:54 CST 2016
     */
    public void setResponsetime(Date responsetime) {
        this.responsetime = responsetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback.UpdateUser
     *
     * @return the value of feedback.UpdateUser
     *
     * @mbggenerated Sun Sep 11 14:51:54 CST 2016
     */
    public String getUpdateuser() {
        return updateuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback.UpdateUser
     *
     * @param updateuser the value for feedback.UpdateUser
     *
     * @mbggenerated Sun Sep 11 14:51:54 CST 2016
     */
    public void setUpdateuser(String updateuser) {
        this.updateuser = updateuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback.UpdateTime
     *
     * @return the value of feedback.UpdateTime
     *
     * @mbggenerated Sun Sep 11 14:51:54 CST 2016
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback.UpdateTime
     *
     * @param updatetime the value for feedback.UpdateTime
     *
     * @mbggenerated Sun Sep 11 14:51:54 CST 2016
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback.FeedBackUser
     *
     * @return the value of feedback.FeedBackUser
     *
     * @mbggenerated Sun Sep 11 14:51:54 CST 2016
     */
    public String getFeedbackuser() {
        return feedbackuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback.FeedBackUser
     *
     * @param feedbackuser the value for feedback.FeedBackUser
     *
     * @mbggenerated Sun Sep 11 14:51:54 CST 2016
     */
    public void setFeedbackuser(String feedbackuser) {
        this.feedbackuser = feedbackuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback.IsShow
     *
     * @return the value of feedback.IsShow
     *
     * @mbggenerated Sun Sep 11 14:51:54 CST 2016
     */
    public Integer getIsshow() {
        return isshow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback.IsShow
     *
     * @param isshow the value for feedback.IsShow
     *
     * @mbggenerated Sun Sep 11 14:51:54 CST 2016
     */
    public void setIsshow(Integer isshow) {
        this.isshow = isshow;
    }
}