package com.cn.cust.entities;

import java.util.Date;

public class Happayteachersdays {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column happayteachersdays.Id
     *
     * @mbggenerated Sat Sep 10 23:42:59 CST 2016
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column happayteachersdays.Content
     *
     * @mbggenerated Sat Sep 10 23:42:59 CST 2016
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column happayteachersdays.Teachers
     *
     * @mbggenerated Sat Sep 10 23:42:59 CST 2016
     */
    private String teachers;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column happayteachersdays.Students
     *
     * @mbggenerated Sat Sep 10 23:42:59 CST 2016
     */
    private String students;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column happayteachersdays.GoodPoints
     *
     * @mbggenerated Sat Sep 10 23:42:59 CST 2016
     */
    private Long goodpoints;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column happayteachersdays.IpAddress
     *
     * @mbggenerated Sat Sep 10 23:42:59 CST 2016
     */
    private String ipaddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column happayteachersdays.UserAgent
     *
     * @mbggenerated Sat Sep 10 23:42:59 CST 2016
     */
    private String useragent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column happayteachersdays.Schools
     *
     * @mbggenerated Sat Sep 10 23:42:59 CST 2016
     */
    private String schools;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column happayteachersdays.DayType
     *
     * @mbggenerated Sat Sep 10 23:42:59 CST 2016
     */
    private Integer daytype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column happayteachersdays.IsShow
     *
     * @mbggenerated Sat Sep 10 23:42:59 CST 2016
     */
    private Integer isshow;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column happayteachersdays.ImagesPath
     *
     * @mbggenerated Sat Sep 10 23:42:59 CST 2016
     */
    private String imagespath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column happayteachersdays.CreateTime
     *
     * @mbggenerated Sat Sep 10 23:42:59 CST 2016
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column happayteachersdays.UpdateTime
     *
     * @mbggenerated Sat Sep 10 23:42:59 CST 2016
     */
    private Date updatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column happayteachersdays.CreateUser
     *
     * @mbggenerated Sat Sep 10 23:42:59 CST 2016
     */
    private String createuser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column happayteachersdays.UpdateUser
     *
     * @mbggenerated Sat Sep 10 23:42:59 CST 2016
     */
    private String updateuser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column happayteachersdays.Id
     *
     * @return the value of happayteachersdays.Id
     *
     * @mbggenerated Sat Sep 10 23:42:59 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column happayteachersdays.Id
     *
     * @param id the value for happayteachersdays.Id
     *
     * @mbggenerated Sat Sep 10 23:42:59 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column happayteachersdays.Content
     *
     * @return the value of happayteachersdays.Content
     *
     * @mbggenerated Sat Sep 10 23:42:59 CST 2016
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column happayteachersdays.Content
     *
     * @param content the value for happayteachersdays.Content
     *
     * @mbggenerated Sat Sep 10 23:42:59 CST 2016
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column happayteachersdays.Teachers
     *
     * @return the value of happayteachersdays.Teachers
     *
     * @mbggenerated Sat Sep 10 23:42:59 CST 2016
     */
    public String getTeachers() {
        return teachers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column happayteachersdays.Teachers
     *
     * @param teachers the value for happayteachersdays.Teachers
     *
     * @mbggenerated Sat Sep 10 23:42:59 CST 2016
     */
    public void setTeachers(String teachers) {
        this.teachers = teachers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column happayteachersdays.Students
     *
     * @return the value of happayteachersdays.Students
     *
     * @mbggenerated Sat Sep 10 23:42:59 CST 2016
     */
    public String getStudents() {
        return students;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column happayteachersdays.Students
     *
     * @param students the value for happayteachersdays.Students
     *
     * @mbggenerated Sat Sep 10 23:42:59 CST 2016
     */
    public void setStudents(String students) {
        this.students = students;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column happayteachersdays.GoodPoints
     *
     * @return the value of happayteachersdays.GoodPoints
     *
     * @mbggenerated Sat Sep 10 23:42:59 CST 2016
     */
    public Long getGoodpoints() {
        return goodpoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column happayteachersdays.GoodPoints
     *
     * @param goodpoints the value for happayteachersdays.GoodPoints
     *
     * @mbggenerated Sat Sep 10 23:42:59 CST 2016
     */
    public void setGoodpoints(Long goodpoints) {
        this.goodpoints = goodpoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column happayteachersdays.IpAddress
     *
     * @return the value of happayteachersdays.IpAddress
     *
     * @mbggenerated Sat Sep 10 23:42:59 CST 2016
     */
    public String getIpaddress() {
        return ipaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column happayteachersdays.IpAddress
     *
     * @param ipaddress the value for happayteachersdays.IpAddress
     *
     * @mbggenerated Sat Sep 10 23:42:59 CST 2016
     */
    public void setIpaddress(String ipaddress) {
        this.ipaddress = ipaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column happayteachersdays.UserAgent
     *
     * @return the value of happayteachersdays.UserAgent
     *
     * @mbggenerated Sat Sep 10 23:42:59 CST 2016
     */
    public String getUseragent() {
        return useragent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column happayteachersdays.UserAgent
     *
     * @param useragent the value for happayteachersdays.UserAgent
     *
     * @mbggenerated Sat Sep 10 23:42:59 CST 2016
     */
    public void setUseragent(String useragent) {
        this.useragent = useragent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column happayteachersdays.Schools
     *
     * @return the value of happayteachersdays.Schools
     *
     * @mbggenerated Sat Sep 10 23:42:59 CST 2016
     */
    public String getSchools() {
        return schools;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column happayteachersdays.Schools
     *
     * @param schools the value for happayteachersdays.Schools
     *
     * @mbggenerated Sat Sep 10 23:42:59 CST 2016
     */
    public void setSchools(String schools) {
        this.schools = schools;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column happayteachersdays.DayType
     *
     * @return the value of happayteachersdays.DayType
     *
     * @mbggenerated Sat Sep 10 23:42:59 CST 2016
     */
    public Integer getDaytype() {
        return daytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column happayteachersdays.DayType
     *
     * @param daytype the value for happayteachersdays.DayType
     *
     * @mbggenerated Sat Sep 10 23:42:59 CST 2016
     */
    public void setDaytype(Integer daytype) {
        this.daytype = daytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column happayteachersdays.IsShow
     *
     * @return the value of happayteachersdays.IsShow
     *
     * @mbggenerated Sat Sep 10 23:42:59 CST 2016
     */
    public Integer getIsshow() {
        return isshow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column happayteachersdays.IsShow
     *
     * @param isshow the value for happayteachersdays.IsShow
     *
     * @mbggenerated Sat Sep 10 23:42:59 CST 2016
     */
    public void setIsshow(Integer isshow) {
        this.isshow = isshow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column happayteachersdays.ImagesPath
     *
     * @return the value of happayteachersdays.ImagesPath
     *
     * @mbggenerated Sat Sep 10 23:42:59 CST 2016
     */
    public String getImagespath() {
        return imagespath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column happayteachersdays.ImagesPath
     *
     * @param imagespath the value for happayteachersdays.ImagesPath
     *
     * @mbggenerated Sat Sep 10 23:42:59 CST 2016
     */
    public void setImagespath(String imagespath) {
        this.imagespath = imagespath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column happayteachersdays.CreateTime
     *
     * @return the value of happayteachersdays.CreateTime
     *
     * @mbggenerated Sat Sep 10 23:42:59 CST 2016
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column happayteachersdays.CreateTime
     *
     * @param createtime the value for happayteachersdays.CreateTime
     *
     * @mbggenerated Sat Sep 10 23:42:59 CST 2016
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column happayteachersdays.UpdateTime
     *
     * @return the value of happayteachersdays.UpdateTime
     *
     * @mbggenerated Sat Sep 10 23:42:59 CST 2016
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column happayteachersdays.UpdateTime
     *
     * @param updatetime the value for happayteachersdays.UpdateTime
     *
     * @mbggenerated Sat Sep 10 23:42:59 CST 2016
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column happayteachersdays.CreateUser
     *
     * @return the value of happayteachersdays.CreateUser
     *
     * @mbggenerated Sat Sep 10 23:42:59 CST 2016
     */
    public String getCreateuser() {
        return createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column happayteachersdays.CreateUser
     *
     * @param createuser the value for happayteachersdays.CreateUser
     *
     * @mbggenerated Sat Sep 10 23:42:59 CST 2016
     */
    public void setCreateuser(String createuser) {
        this.createuser = createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column happayteachersdays.UpdateUser
     *
     * @return the value of happayteachersdays.UpdateUser
     *
     * @mbggenerated Sat Sep 10 23:42:59 CST 2016
     */
    public String getUpdateuser() {
        return updateuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column happayteachersdays.UpdateUser
     *
     * @param updateuser the value for happayteachersdays.UpdateUser
     *
     * @mbggenerated Sat Sep 10 23:42:59 CST 2016
     */
    public void setUpdateuser(String updateuser) {
        this.updateuser = updateuser;
    }
}