package com.cn.cust.entities;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class HappayteachersdaysExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table happayteachersdays
     *
     * @mbggenerated Sat Sep 10 23:42:59 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table happayteachersdays
     *
     * @mbggenerated Sat Sep 10 23:42:59 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table happayteachersdays
     *
     * @mbggenerated Sat Sep 10 23:42:59 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table happayteachersdays
     *
     * @mbggenerated Sat Sep 10 23:42:59 CST 2016
     */
    public HappayteachersdaysExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table happayteachersdays
     *
     * @mbggenerated Sat Sep 10 23:42:59 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table happayteachersdays
     *
     * @mbggenerated Sat Sep 10 23:42:59 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table happayteachersdays
     *
     * @mbggenerated Sat Sep 10 23:42:59 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table happayteachersdays
     *
     * @mbggenerated Sat Sep 10 23:42:59 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table happayteachersdays
     *
     * @mbggenerated Sat Sep 10 23:42:59 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table happayteachersdays
     *
     * @mbggenerated Sat Sep 10 23:42:59 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table happayteachersdays
     *
     * @mbggenerated Sat Sep 10 23:42:59 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table happayteachersdays
     *
     * @mbggenerated Sat Sep 10 23:42:59 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table happayteachersdays
     *
     * @mbggenerated Sat Sep 10 23:42:59 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table happayteachersdays
     *
     * @mbggenerated Sat Sep 10 23:42:59 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table happayteachersdays
     *
     * @mbggenerated Sat Sep 10 23:42:59 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("Id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("Id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("Id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("Id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("Id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("Id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("Id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("Id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("Id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("Id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("Id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("Id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andContentIsNull() {
            addCriterion("Content is null");
            return (Criteria) this;
        }

        public Criteria andContentIsNotNull() {
            addCriterion("Content is not null");
            return (Criteria) this;
        }

        public Criteria andContentEqualTo(String value) {
            addCriterion("Content =", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotEqualTo(String value) {
            addCriterion("Content <>", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentGreaterThan(String value) {
            addCriterion("Content >", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentGreaterThanOrEqualTo(String value) {
            addCriterion("Content >=", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLessThan(String value) {
            addCriterion("Content <", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLessThanOrEqualTo(String value) {
            addCriterion("Content <=", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLike(String value) {
            addCriterion("Content like", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotLike(String value) {
            addCriterion("Content not like", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentIn(List<String> values) {
            addCriterion("Content in", values, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotIn(List<String> values) {
            addCriterion("Content not in", values, "content");
            return (Criteria) this;
        }

        public Criteria andContentBetween(String value1, String value2) {
            addCriterion("Content between", value1, value2, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotBetween(String value1, String value2) {
            addCriterion("Content not between", value1, value2, "content");
            return (Criteria) this;
        }

        public Criteria andTeachersIsNull() {
            addCriterion("Teachers is null");
            return (Criteria) this;
        }

        public Criteria andTeachersIsNotNull() {
            addCriterion("Teachers is not null");
            return (Criteria) this;
        }

        public Criteria andTeachersEqualTo(String value) {
            addCriterion("Teachers =", value, "teachers");
            return (Criteria) this;
        }

        public Criteria andTeachersNotEqualTo(String value) {
            addCriterion("Teachers <>", value, "teachers");
            return (Criteria) this;
        }

        public Criteria andTeachersGreaterThan(String value) {
            addCriterion("Teachers >", value, "teachers");
            return (Criteria) this;
        }

        public Criteria andTeachersGreaterThanOrEqualTo(String value) {
            addCriterion("Teachers >=", value, "teachers");
            return (Criteria) this;
        }

        public Criteria andTeachersLessThan(String value) {
            addCriterion("Teachers <", value, "teachers");
            return (Criteria) this;
        }

        public Criteria andTeachersLessThanOrEqualTo(String value) {
            addCriterion("Teachers <=", value, "teachers");
            return (Criteria) this;
        }

        public Criteria andTeachersLike(String value) {
            addCriterion("Teachers like", value, "teachers");
            return (Criteria) this;
        }

        public Criteria andTeachersNotLike(String value) {
            addCriterion("Teachers not like", value, "teachers");
            return (Criteria) this;
        }

        public Criteria andTeachersIn(List<String> values) {
            addCriterion("Teachers in", values, "teachers");
            return (Criteria) this;
        }

        public Criteria andTeachersNotIn(List<String> values) {
            addCriterion("Teachers not in", values, "teachers");
            return (Criteria) this;
        }

        public Criteria andTeachersBetween(String value1, String value2) {
            addCriterion("Teachers between", value1, value2, "teachers");
            return (Criteria) this;
        }

        public Criteria andTeachersNotBetween(String value1, String value2) {
            addCriterion("Teachers not between", value1, value2, "teachers");
            return (Criteria) this;
        }

        public Criteria andStudentsIsNull() {
            addCriterion("Students is null");
            return (Criteria) this;
        }

        public Criteria andStudentsIsNotNull() {
            addCriterion("Students is not null");
            return (Criteria) this;
        }

        public Criteria andStudentsEqualTo(String value) {
            addCriterion("Students =", value, "students");
            return (Criteria) this;
        }

        public Criteria andStudentsNotEqualTo(String value) {
            addCriterion("Students <>", value, "students");
            return (Criteria) this;
        }

        public Criteria andStudentsGreaterThan(String value) {
            addCriterion("Students >", value, "students");
            return (Criteria) this;
        }

        public Criteria andStudentsGreaterThanOrEqualTo(String value) {
            addCriterion("Students >=", value, "students");
            return (Criteria) this;
        }

        public Criteria andStudentsLessThan(String value) {
            addCriterion("Students <", value, "students");
            return (Criteria) this;
        }

        public Criteria andStudentsLessThanOrEqualTo(String value) {
            addCriterion("Students <=", value, "students");
            return (Criteria) this;
        }

        public Criteria andStudentsLike(String value) {
            addCriterion("Students like", value, "students");
            return (Criteria) this;
        }

        public Criteria andStudentsNotLike(String value) {
            addCriterion("Students not like", value, "students");
            return (Criteria) this;
        }

        public Criteria andStudentsIn(List<String> values) {
            addCriterion("Students in", values, "students");
            return (Criteria) this;
        }

        public Criteria andStudentsNotIn(List<String> values) {
            addCriterion("Students not in", values, "students");
            return (Criteria) this;
        }

        public Criteria andStudentsBetween(String value1, String value2) {
            addCriterion("Students between", value1, value2, "students");
            return (Criteria) this;
        }

        public Criteria andStudentsNotBetween(String value1, String value2) {
            addCriterion("Students not between", value1, value2, "students");
            return (Criteria) this;
        }

        public Criteria andGoodpointsIsNull() {
            addCriterion("GoodPoints is null");
            return (Criteria) this;
        }

        public Criteria andGoodpointsIsNotNull() {
            addCriterion("GoodPoints is not null");
            return (Criteria) this;
        }

        public Criteria andGoodpointsEqualTo(Long value) {
            addCriterion("GoodPoints =", value, "goodpoints");
            return (Criteria) this;
        }

        public Criteria andGoodpointsNotEqualTo(Long value) {
            addCriterion("GoodPoints <>", value, "goodpoints");
            return (Criteria) this;
        }

        public Criteria andGoodpointsGreaterThan(Long value) {
            addCriterion("GoodPoints >", value, "goodpoints");
            return (Criteria) this;
        }

        public Criteria andGoodpointsGreaterThanOrEqualTo(Long value) {
            addCriterion("GoodPoints >=", value, "goodpoints");
            return (Criteria) this;
        }

        public Criteria andGoodpointsLessThan(Long value) {
            addCriterion("GoodPoints <", value, "goodpoints");
            return (Criteria) this;
        }

        public Criteria andGoodpointsLessThanOrEqualTo(Long value) {
            addCriterion("GoodPoints <=", value, "goodpoints");
            return (Criteria) this;
        }

        public Criteria andGoodpointsIn(List<Long> values) {
            addCriterion("GoodPoints in", values, "goodpoints");
            return (Criteria) this;
        }

        public Criteria andGoodpointsNotIn(List<Long> values) {
            addCriterion("GoodPoints not in", values, "goodpoints");
            return (Criteria) this;
        }

        public Criteria andGoodpointsBetween(Long value1, Long value2) {
            addCriterion("GoodPoints between", value1, value2, "goodpoints");
            return (Criteria) this;
        }

        public Criteria andGoodpointsNotBetween(Long value1, Long value2) {
            addCriterion("GoodPoints not between", value1, value2, "goodpoints");
            return (Criteria) this;
        }

        public Criteria andIpaddressIsNull() {
            addCriterion("IpAddress is null");
            return (Criteria) this;
        }

        public Criteria andIpaddressIsNotNull() {
            addCriterion("IpAddress is not null");
            return (Criteria) this;
        }

        public Criteria andIpaddressEqualTo(String value) {
            addCriterion("IpAddress =", value, "ipaddress");
            return (Criteria) this;
        }

        public Criteria andIpaddressNotEqualTo(String value) {
            addCriterion("IpAddress <>", value, "ipaddress");
            return (Criteria) this;
        }

        public Criteria andIpaddressGreaterThan(String value) {
            addCriterion("IpAddress >", value, "ipaddress");
            return (Criteria) this;
        }

        public Criteria andIpaddressGreaterThanOrEqualTo(String value) {
            addCriterion("IpAddress >=", value, "ipaddress");
            return (Criteria) this;
        }

        public Criteria andIpaddressLessThan(String value) {
            addCriterion("IpAddress <", value, "ipaddress");
            return (Criteria) this;
        }

        public Criteria andIpaddressLessThanOrEqualTo(String value) {
            addCriterion("IpAddress <=", value, "ipaddress");
            return (Criteria) this;
        }

        public Criteria andIpaddressLike(String value) {
            addCriterion("IpAddress like", value, "ipaddress");
            return (Criteria) this;
        }

        public Criteria andIpaddressNotLike(String value) {
            addCriterion("IpAddress not like", value, "ipaddress");
            return (Criteria) this;
        }

        public Criteria andIpaddressIn(List<String> values) {
            addCriterion("IpAddress in", values, "ipaddress");
            return (Criteria) this;
        }

        public Criteria andIpaddressNotIn(List<String> values) {
            addCriterion("IpAddress not in", values, "ipaddress");
            return (Criteria) this;
        }

        public Criteria andIpaddressBetween(String value1, String value2) {
            addCriterion("IpAddress between", value1, value2, "ipaddress");
            return (Criteria) this;
        }

        public Criteria andIpaddressNotBetween(String value1, String value2) {
            addCriterion("IpAddress not between", value1, value2, "ipaddress");
            return (Criteria) this;
        }

        public Criteria andUseragentIsNull() {
            addCriterion("UserAgent is null");
            return (Criteria) this;
        }

        public Criteria andUseragentIsNotNull() {
            addCriterion("UserAgent is not null");
            return (Criteria) this;
        }

        public Criteria andUseragentEqualTo(String value) {
            addCriterion("UserAgent =", value, "useragent");
            return (Criteria) this;
        }

        public Criteria andUseragentNotEqualTo(String value) {
            addCriterion("UserAgent <>", value, "useragent");
            return (Criteria) this;
        }

        public Criteria andUseragentGreaterThan(String value) {
            addCriterion("UserAgent >", value, "useragent");
            return (Criteria) this;
        }

        public Criteria andUseragentGreaterThanOrEqualTo(String value) {
            addCriterion("UserAgent >=", value, "useragent");
            return (Criteria) this;
        }

        public Criteria andUseragentLessThan(String value) {
            addCriterion("UserAgent <", value, "useragent");
            return (Criteria) this;
        }

        public Criteria andUseragentLessThanOrEqualTo(String value) {
            addCriterion("UserAgent <=", value, "useragent");
            return (Criteria) this;
        }

        public Criteria andUseragentLike(String value) {
            addCriterion("UserAgent like", value, "useragent");
            return (Criteria) this;
        }

        public Criteria andUseragentNotLike(String value) {
            addCriterion("UserAgent not like", value, "useragent");
            return (Criteria) this;
        }

        public Criteria andUseragentIn(List<String> values) {
            addCriterion("UserAgent in", values, "useragent");
            return (Criteria) this;
        }

        public Criteria andUseragentNotIn(List<String> values) {
            addCriterion("UserAgent not in", values, "useragent");
            return (Criteria) this;
        }

        public Criteria andUseragentBetween(String value1, String value2) {
            addCriterion("UserAgent between", value1, value2, "useragent");
            return (Criteria) this;
        }

        public Criteria andUseragentNotBetween(String value1, String value2) {
            addCriterion("UserAgent not between", value1, value2, "useragent");
            return (Criteria) this;
        }

        public Criteria andSchoolsIsNull() {
            addCriterion("Schools is null");
            return (Criteria) this;
        }

        public Criteria andSchoolsIsNotNull() {
            addCriterion("Schools is not null");
            return (Criteria) this;
        }

        public Criteria andSchoolsEqualTo(String value) {
            addCriterion("Schools =", value, "schools");
            return (Criteria) this;
        }

        public Criteria andSchoolsNotEqualTo(String value) {
            addCriterion("Schools <>", value, "schools");
            return (Criteria) this;
        }

        public Criteria andSchoolsGreaterThan(String value) {
            addCriterion("Schools >", value, "schools");
            return (Criteria) this;
        }

        public Criteria andSchoolsGreaterThanOrEqualTo(String value) {
            addCriterion("Schools >=", value, "schools");
            return (Criteria) this;
        }

        public Criteria andSchoolsLessThan(String value) {
            addCriterion("Schools <", value, "schools");
            return (Criteria) this;
        }

        public Criteria andSchoolsLessThanOrEqualTo(String value) {
            addCriterion("Schools <=", value, "schools");
            return (Criteria) this;
        }

        public Criteria andSchoolsLike(String value) {
            addCriterion("Schools like", value, "schools");
            return (Criteria) this;
        }

        public Criteria andSchoolsNotLike(String value) {
            addCriterion("Schools not like", value, "schools");
            return (Criteria) this;
        }

        public Criteria andSchoolsIn(List<String> values) {
            addCriterion("Schools in", values, "schools");
            return (Criteria) this;
        }

        public Criteria andSchoolsNotIn(List<String> values) {
            addCriterion("Schools not in", values, "schools");
            return (Criteria) this;
        }

        public Criteria andSchoolsBetween(String value1, String value2) {
            addCriterion("Schools between", value1, value2, "schools");
            return (Criteria) this;
        }

        public Criteria andSchoolsNotBetween(String value1, String value2) {
            addCriterion("Schools not between", value1, value2, "schools");
            return (Criteria) this;
        }

        public Criteria andDaytypeIsNull() {
            addCriterion("DayType is null");
            return (Criteria) this;
        }

        public Criteria andDaytypeIsNotNull() {
            addCriterion("DayType is not null");
            return (Criteria) this;
        }

        public Criteria andDaytypeEqualTo(Integer value) {
            addCriterion("DayType =", value, "daytype");
            return (Criteria) this;
        }

        public Criteria andDaytypeNotEqualTo(Integer value) {
            addCriterion("DayType <>", value, "daytype");
            return (Criteria) this;
        }

        public Criteria andDaytypeGreaterThan(Integer value) {
            addCriterion("DayType >", value, "daytype");
            return (Criteria) this;
        }

        public Criteria andDaytypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("DayType >=", value, "daytype");
            return (Criteria) this;
        }

        public Criteria andDaytypeLessThan(Integer value) {
            addCriterion("DayType <", value, "daytype");
            return (Criteria) this;
        }

        public Criteria andDaytypeLessThanOrEqualTo(Integer value) {
            addCriterion("DayType <=", value, "daytype");
            return (Criteria) this;
        }

        public Criteria andDaytypeIn(List<Integer> values) {
            addCriterion("DayType in", values, "daytype");
            return (Criteria) this;
        }

        public Criteria andDaytypeNotIn(List<Integer> values) {
            addCriterion("DayType not in", values, "daytype");
            return (Criteria) this;
        }

        public Criteria andDaytypeBetween(Integer value1, Integer value2) {
            addCriterion("DayType between", value1, value2, "daytype");
            return (Criteria) this;
        }

        public Criteria andDaytypeNotBetween(Integer value1, Integer value2) {
            addCriterion("DayType not between", value1, value2, "daytype");
            return (Criteria) this;
        }

        public Criteria andIsshowIsNull() {
            addCriterion("IsShow is null");
            return (Criteria) this;
        }

        public Criteria andIsshowIsNotNull() {
            addCriterion("IsShow is not null");
            return (Criteria) this;
        }

        public Criteria andIsshowEqualTo(Integer value) {
            addCriterion("IsShow =", value, "isshow");
            return (Criteria) this;
        }

        public Criteria andIsshowNotEqualTo(Integer value) {
            addCriterion("IsShow <>", value, "isshow");
            return (Criteria) this;
        }

        public Criteria andIsshowGreaterThan(Integer value) {
            addCriterion("IsShow >", value, "isshow");
            return (Criteria) this;
        }

        public Criteria andIsshowGreaterThanOrEqualTo(Integer value) {
            addCriterion("IsShow >=", value, "isshow");
            return (Criteria) this;
        }

        public Criteria andIsshowLessThan(Integer value) {
            addCriterion("IsShow <", value, "isshow");
            return (Criteria) this;
        }

        public Criteria andIsshowLessThanOrEqualTo(Integer value) {
            addCriterion("IsShow <=", value, "isshow");
            return (Criteria) this;
        }

        public Criteria andIsshowIn(List<Integer> values) {
            addCriterion("IsShow in", values, "isshow");
            return (Criteria) this;
        }

        public Criteria andIsshowNotIn(List<Integer> values) {
            addCriterion("IsShow not in", values, "isshow");
            return (Criteria) this;
        }

        public Criteria andIsshowBetween(Integer value1, Integer value2) {
            addCriterion("IsShow between", value1, value2, "isshow");
            return (Criteria) this;
        }

        public Criteria andIsshowNotBetween(Integer value1, Integer value2) {
            addCriterion("IsShow not between", value1, value2, "isshow");
            return (Criteria) this;
        }

        public Criteria andImagespathIsNull() {
            addCriterion("ImagesPath is null");
            return (Criteria) this;
        }

        public Criteria andImagespathIsNotNull() {
            addCriterion("ImagesPath is not null");
            return (Criteria) this;
        }

        public Criteria andImagespathEqualTo(String value) {
            addCriterion("ImagesPath =", value, "imagespath");
            return (Criteria) this;
        }

        public Criteria andImagespathNotEqualTo(String value) {
            addCriterion("ImagesPath <>", value, "imagespath");
            return (Criteria) this;
        }

        public Criteria andImagespathGreaterThan(String value) {
            addCriterion("ImagesPath >", value, "imagespath");
            return (Criteria) this;
        }

        public Criteria andImagespathGreaterThanOrEqualTo(String value) {
            addCriterion("ImagesPath >=", value, "imagespath");
            return (Criteria) this;
        }

        public Criteria andImagespathLessThan(String value) {
            addCriterion("ImagesPath <", value, "imagespath");
            return (Criteria) this;
        }

        public Criteria andImagespathLessThanOrEqualTo(String value) {
            addCriterion("ImagesPath <=", value, "imagespath");
            return (Criteria) this;
        }

        public Criteria andImagespathLike(String value) {
            addCriterion("ImagesPath like", value, "imagespath");
            return (Criteria) this;
        }

        public Criteria andImagespathNotLike(String value) {
            addCriterion("ImagesPath not like", value, "imagespath");
            return (Criteria) this;
        }

        public Criteria andImagespathIn(List<String> values) {
            addCriterion("ImagesPath in", values, "imagespath");
            return (Criteria) this;
        }

        public Criteria andImagespathNotIn(List<String> values) {
            addCriterion("ImagesPath not in", values, "imagespath");
            return (Criteria) this;
        }

        public Criteria andImagespathBetween(String value1, String value2) {
            addCriterion("ImagesPath between", value1, value2, "imagespath");
            return (Criteria) this;
        }

        public Criteria andImagespathNotBetween(String value1, String value2) {
            addCriterion("ImagesPath not between", value1, value2, "imagespath");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNull() {
            addCriterion("CreateTime is null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNotNull() {
            addCriterion("CreateTime is not null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeEqualTo(Date value) {
            addCriterion("CreateTime =", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotEqualTo(Date value) {
            addCriterion("CreateTime <>", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThan(Date value) {
            addCriterion("CreateTime >", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CreateTime >=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThan(Date value) {
            addCriterion("CreateTime <", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThanOrEqualTo(Date value) {
            addCriterion("CreateTime <=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIn(List<Date> values) {
            addCriterion("CreateTime in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotIn(List<Date> values) {
            addCriterion("CreateTime not in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeBetween(Date value1, Date value2) {
            addCriterion("CreateTime between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotBetween(Date value1, Date value2) {
            addCriterion("CreateTime not between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIsNull() {
            addCriterion("UpdateTime is null");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIsNotNull() {
            addCriterion("UpdateTime is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeEqualTo(Date value) {
            addCriterion("UpdateTime =", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotEqualTo(Date value) {
            addCriterion("UpdateTime <>", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeGreaterThan(Date value) {
            addCriterion("UpdateTime >", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("UpdateTime >=", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeLessThan(Date value) {
            addCriterion("UpdateTime <", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeLessThanOrEqualTo(Date value) {
            addCriterion("UpdateTime <=", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIn(List<Date> values) {
            addCriterion("UpdateTime in", values, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotIn(List<Date> values) {
            addCriterion("UpdateTime not in", values, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeBetween(Date value1, Date value2) {
            addCriterion("UpdateTime between", value1, value2, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotBetween(Date value1, Date value2) {
            addCriterion("UpdateTime not between", value1, value2, "updatetime");
            return (Criteria) this;
        }

        public Criteria andCreateuserIsNull() {
            addCriterion("CreateUser is null");
            return (Criteria) this;
        }

        public Criteria andCreateuserIsNotNull() {
            addCriterion("CreateUser is not null");
            return (Criteria) this;
        }

        public Criteria andCreateuserEqualTo(String value) {
            addCriterion("CreateUser =", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserNotEqualTo(String value) {
            addCriterion("CreateUser <>", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserGreaterThan(String value) {
            addCriterion("CreateUser >", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserGreaterThanOrEqualTo(String value) {
            addCriterion("CreateUser >=", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserLessThan(String value) {
            addCriterion("CreateUser <", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserLessThanOrEqualTo(String value) {
            addCriterion("CreateUser <=", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserLike(String value) {
            addCriterion("CreateUser like", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserNotLike(String value) {
            addCriterion("CreateUser not like", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserIn(List<String> values) {
            addCriterion("CreateUser in", values, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserNotIn(List<String> values) {
            addCriterion("CreateUser not in", values, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserBetween(String value1, String value2) {
            addCriterion("CreateUser between", value1, value2, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserNotBetween(String value1, String value2) {
            addCriterion("CreateUser not between", value1, value2, "createuser");
            return (Criteria) this;
        }

        public Criteria andUpdateuserIsNull() {
            addCriterion("UpdateUser is null");
            return (Criteria) this;
        }

        public Criteria andUpdateuserIsNotNull() {
            addCriterion("UpdateUser is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateuserEqualTo(String value) {
            addCriterion("UpdateUser =", value, "updateuser");
            return (Criteria) this;
        }

        public Criteria andUpdateuserNotEqualTo(String value) {
            addCriterion("UpdateUser <>", value, "updateuser");
            return (Criteria) this;
        }

        public Criteria andUpdateuserGreaterThan(String value) {
            addCriterion("UpdateUser >", value, "updateuser");
            return (Criteria) this;
        }

        public Criteria andUpdateuserGreaterThanOrEqualTo(String value) {
            addCriterion("UpdateUser >=", value, "updateuser");
            return (Criteria) this;
        }

        public Criteria andUpdateuserLessThan(String value) {
            addCriterion("UpdateUser <", value, "updateuser");
            return (Criteria) this;
        }

        public Criteria andUpdateuserLessThanOrEqualTo(String value) {
            addCriterion("UpdateUser <=", value, "updateuser");
            return (Criteria) this;
        }

        public Criteria andUpdateuserLike(String value) {
            addCriterion("UpdateUser like", value, "updateuser");
            return (Criteria) this;
        }

        public Criteria andUpdateuserNotLike(String value) {
            addCriterion("UpdateUser not like", value, "updateuser");
            return (Criteria) this;
        }

        public Criteria andUpdateuserIn(List<String> values) {
            addCriterion("UpdateUser in", values, "updateuser");
            return (Criteria) this;
        }

        public Criteria andUpdateuserNotIn(List<String> values) {
            addCriterion("UpdateUser not in", values, "updateuser");
            return (Criteria) this;
        }

        public Criteria andUpdateuserBetween(String value1, String value2) {
            addCriterion("UpdateUser between", value1, value2, "updateuser");
            return (Criteria) this;
        }

        public Criteria andUpdateuserNotBetween(String value1, String value2) {
            addCriterion("UpdateUser not between", value1, value2, "updateuser");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table happayteachersdays
     *
     * @mbggenerated do_not_delete_during_merge Sat Sep 10 23:42:59 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table happayteachersdays
     *
     * @mbggenerated Sat Sep 10 23:42:59 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}